version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: access_control
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/opt/backups
    #ports:
    #  - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d access_control"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://admin:admin123@db:5432/access_control
      - SECRET_KEY=your-secret-key-change-this-in-production
    volumes:
      - ./app:/app/app
      - ./templates:/app/templates
      - ./static:/app/static
    command: >
      sh -c "
        alembic upgrade head &&
        python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  postgres_data:
